---
title: "Exploring Bcell markers in Amezcua 2019 dataset"
author: "A. Berenstein"
date: "22/04/2022"
output:
  rmdformats::readthedown:
    self-contained: true
    highlight: haddock
    thumbnails: false
    css: styles.css
knit: (function(input_file, encoding) {
  out_dir <- 'docs';
  rmarkdown::render(input_file, encoding=encoding,
 output_file=file.path(dirname(input_file), out_dir, 'gene_subsets_v05122022.html'))})
---


```{r, message=F, warning=F,results=F}
renv::activate()
renv::restore()

library(Seurat)
library(dplyr)
library(UCell)
library(scGate)
library(ggplot2)
library(patchwork)
library(SeuratDisk)
library(ProjecTILs)
library(glmGamPoi)
source("./utils.R")
```


# Load Bcell-filtered dataset
```{r,warning=F, collapse =T,message =F,eval=F}
ndim = 30; seed = 31416
panBellFile <-  "~/Dropbox/Amezcua/processed_data/PanBcellSubset.rds"  # Subseted Pan Bcell FIle with recomputed UMAP
data <- readRDS(panBellFile)
data%>%dim
data <- data%>%subset(panBcell2HR == "Pure")
data%>%dim
data$condition <- ifelse(data$orig.ident == "DS-017-WT","wt","im") 
data.bkp <- data
data.wt <- data%>%subset(orig.ident == "DS-017-WT")
data.im <- data%>%subset(orig.ident != "DS-017-WT")
```

# Preprocessing

```{r,warning=F, collapse =T,message =F, results='hide',eval=F}
# extract cell cycle genes from Seurat 
s.genes <- cc.genes$s.genes%>%hs.2.mm(.)
g2m.genes <- cc.genes$g2m.genes%>%hs.2.mm(.)
```

```{r,warning=F, collapse =T,message =F,results='hide'}
# IM
set.seed(seed)
data.im <- CellCycleScoring(data.im, s.features = s.genes, g2m.features = g2m.genes, set.ident = TRUE)
data.im$CC.Difference <- data.im$S.Score - data.im$G2M.Score
data.im <- SCTransform(data.im, method = "glmGamPoi", vars.to.regress = c("percent.mito","CC.Difference"), verbose = FALSE)
data.im <- RunPCA(data.im, features = data.im@assays$RNA@var.features,
                ndims.print = 1:5, nfeatures.print = 5)
data.im <- RunUMAP(data.im, reduction = "pca", dims = 1:ndim, seed.use=seed, n.neighbors = 20)

```


```{r,warning=F, collapse =T,message =F, results='hide'}
# WT
set.seed(seed)
data.wt <- CellCycleScoring(data.wt, s.features = s.genes, g2m.features = g2m.genes, set.ident = TRUE)
data.wt$CC.Difference <- data.wt$S.Score - data.wt$G2M.Score
data.wt <- SCTransform(data.wt, method = "glmGamPoi", vars.to.regress = c("percent.mito","CC.Difference"), verbose = FALSE)
data.wt <- RunPCA(data.wt, features = data.wt@assays$RNA@var.features,
                ndims.print = 1:5, nfeatures.print = 5)
data.wt <- RunUMAP(data.wt, reduction = "pca", dims = 1:ndim, seed.use=seed, n.neighbors = 20)


```


# Unsupervised analysis
```{r,fig.height=4, fig.width= 10,warning=F, collapse =T,message =F, results='hide'}
set.seed(seed)
data.im <- FindNeighbors(data.im,assay  = "SCT", dims = 1:20)
data.im <- FindClusters(data.im, resolution = 0.7)
data.im <- FindClusters(data.im, resolution = 0.5)
data.im <- FindClusters(data.im, resolution = 0.4)
data.im <- FindClusters(data.im, resolution = 0.3)

set.seed(seed)
data.wt <- FindNeighbors(data.wt,assay  = "SCT", dims = 1:20)
data.wt <- FindClusters(data.wt, resolution = 2)
data.wt <- FindClusters(data.wt, resolution = 1.5)
data.wt <- FindClusters(data.wt, resolution = 1)
data.wt <- FindClusters(data.wt, resolution = 0.9)
data.wt <- FindClusters(data.wt, resolution = 0.8)
data.wt <- FindClusters(data.wt, resolution = 0.75)

data.wt <- FindClusters(data.wt, resolution = 0.7)

data.wt <- FindClusters(data.wt, resolution = 0.6)
data.wt <- FindClusters(data.wt, resolution = 0.65)

data.wt <- FindClusters(data.wt, resolution = 0.5)
data.wt <- FindClusters(data.wt, resolution = 0.4)
data.wt <- FindClusters(data.wt, resolution = 0.3)

a <- DimPlot(data.wt,group.by = "SCT_snn_res.0.8",label = T)
b <- DimPlot(data.im ,group.by = "SCT_snn_res.0.3",label = T)
a + b
```


```{r,fig.height= 12,fig.width=10,warning=F, collapse =T,message =F}
#Idents(data.wt) <- "SCT_snn_res.0.8"
#discrim.wt <- FindAllMarkers(data.wt, only.pos = TRUE, min.pct = 0.25, logfc.threshold = 0.25)
#gene.wt <- discrim.wt$gene
#d <- DoHeatmap(data.wt,features = gene.wt)

#Idents(data.im) <- "SCT_snn_res.0.3"
#discrim.im <- FindAllMarkers(data.im,assay = "SCT", only.pos = T, min.pct = 0.40, logfc.threshold = 0.25)
#gene.im <- discrim.im$gene
#e <- DoHeatmap(data.im,features = gene.im,size = 3,lines.width = 35)

# show WT heatmap
#d 

# show IM heatmap
#e 

```


# Explore predefined markers 
We will use here those genes previously defined in our molecular signature spreadsheet file

```{r,fig.height=15,fig.width=15,warning=F, collapse =T,message =F}
features2 <- c("Cd22","Id3","Cd79b","Spib","H2-Aa","Pax5","Atf6","Irf4","Ighg1","Ighg2b","Ighg2c","Ighg3","Ighd1-1","Ighd2-3","Ighd4-1")
```


```{r,fig.height=15,fig.width=15,warning=F, collapse =T,message =F,eval=F}
for(f in features2){
  print(data%>%rownames()%>%grep(f,.,value = T))
}
```

WT dataset (new genes)
```{r,fig.height=10,fig.width=10,warning=F, collapse =T,message =F}
wtfig = FeaturePlot(data.wt,features = features2, ncol = 3,pt.size = 0.4)
wtfig
ggsave(wtfig,filename = "./docs/WT_gene_plots_0512.png",width = 10,height = 12,dpi = 300)
```

IM dataset (new genes)
```{r,fig.height=12,fig.width=12,warning=F, collapse =T,message =F}
imfig = FeaturePlot(data.im,features = features2, ncol = 3,pt.size = 0.4)
ggsave(imfig,filename = "./docs/IM_gene_plots_0512.png",width = 10,height = 12,dpi = 300)

```

```{r,eval=F,echo=F,message=F}
#write.table(data%>%rownames(),file = "genes.tsv",row.names =F,col.names = F,quote =F)
```


